const MYSQL_ENV_HOST = '167.99.65.65';
const MYSQL_ENV_USERNAME = 'root';
const MYSQL_ENV_PASSWORD = 'Quy1407@';

module.exports = {
    MYSQL_ENV_USERNAME,
    MYSQL_ENV_HOST,
    MYSQL_ENV_PASSWORD
}